ChatbotWebsite/journal/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


# Journal Form
class JournalForm(FlaskForm):
    mood = StringField(
        "How are you feeling?", validators=[DataRequired(), Length(max=30)]
    )
    content = TextAreaField(
        "Express more!", validators=[DataRequired(), Length(max=3000)]
    )
    submit = SubmitField("Submit")

ChatbotWebsite/chatbot/routes.py
from flask import Blueprint, render_template, request, jsonify, url_for, flash, redirect
from flask_login import current_user
from ChatbotWebsite import db
from ChatbotWebsite.chatbot.chatbot import *
from ChatbotWebsite.chatbot.topic import *
from ChatbotWebsite.chatbot.test import *
from ChatbotWebsite.chatbot.mindfulness import *
from ChatbotWebsite.models import ChatMessage

chatbot = Blueprint("chatbot", __name__)


# Chat Page (Main Page)
@chatbot.route("/chat")
def chat():
    messages = None
    if current_user.is_authenticated:
        messages = ChatMessage.query.filter_by(user_id=current_user.id).all()
    return render_template(
        "chat/chat.html",
        title="Chat",
        topics=topics,
        messages=messages,
        tests=tests,
        mindfulness_exercises=mindfulness_exercises,
    )


# Chat Messages, Post reqeust, get response from chatbot and add both messages to database
@chatbot.route("/chat_messages", methods=["POST"])
def chatting():
    message = request.form["msg"]
    response = get_response(message)
    if current_user.is_authenticated:
        user_message = ChatMessage(sender="user", message=message, user=current_user)
        bot_message = ChatMessage(sender="bot", message=response, user=current_user)
        db.session.add(user_message)
        db.session.add(bot_message)
        db.session.commit()
    return jsonify({"msg": response})


# Topic, Post request, get contents from topic and add all messages to database
@chatbot.route("/topic", methods=["POST"])
def topic():
    title = request.form["title"]
    contents = get_content(title)
    if current_user.is_authenticated:
        user_message = ChatMessage(sender="user", message=title, user=current_user)
        db.session.add(user_message)
        for content in contents:
            bot_message = ChatMessage(sender="bot", message=content, user=current_user)
            db.session.add(bot_message)
        db.session.commit()
    return jsonify({"contents": contents})


# Test, Post request, get questions from test
@chatbot.route("/test", methods=["POST"])
def test():
    title = request.form["title"]
    questions = get_questions(title)
    if current_user.is_authenticated:
        user_message = ChatMessage(sender="user", message=title, user=current_user)
        db.session.add(user_message)
        db.session.commit()
    return jsonify({"questions": questions})


# Test Score, Post request, get score message from test and add result to database
@chatbot.route("/score", methods=["POST"])
def score():
    score = request.form["score"]
    title = request.form["title"]
    score_message = get_test_messages(title, score)
    if current_user.is_authenticated:
        bot_score_message = ChatMessage(
            sender="bot", message=score_message, user=current_user
        )
        db.session.add(bot_score_message)
        db.session.commit()
    return jsonify({"score_message": score_message})


# Mindfulness, Post request, get description, file_name from mindfulness exercise
@chatbot.route("/mindfulness", methods=["POST"])
def mindfulness():
    title = request.form["title"]
    description, file_name = get_description(title)
    return jsonify({"description": description, "file_name": file_name})

ChatbotWebsite/journal/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import current_user, login_required
from ChatbotWebsite.models import Journal
from ChatbotWebsite.journal.forms import JournalForm
from ChatbotWebsite import db

journals = Blueprint("journals", __name__)


# All Journals Page
@journals.route("/all_journals")
@login_required
def all_journals():
    page = request.args.get("page", 1, type=int)  # Pagination
    journals = (
        Journal.query.filter_by(user_id=current_user.id)
        .order_by(Journal.timestamp.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("all_journals.html", title="Journals", journals=journals)


# New Journal Page
@journals.route("/journal/new", methods=["GET", "POST"])
@login_required
def new_journal():
    form = JournalForm()  # Create Journal Form
    if (
        form.validate_on_submit()
    ):  # If form is submitted, create new journal and add to database
        flash("Journal has been created!", "success")
        journal = Journal(
            mood=form.mood.data, content=form.content.data, user=current_user
        )
        db.session.add(journal)
        db.session.commit()
        return redirect(url_for("journals.all_journals"))
    return render_template(
        "create_journal.html", title="New Journal", legend="New Journal", form=form
    )


# Journal Page
@journals.route("/journal/<int:journal_id>")
@login_required
def journal(journal_id):
    journal = Journal.query.get_or_404(journal_id)  # Get journal from database
    if (
        journal.user != current_user
    ):  # If journal does not belong to current user, abort
        abort(403)
    return render_template(
        "journal.html", title="Journal #" + str(journal.id), journal=journal
    )


# Update Journal Page
@journals.route("/journal/<int:journal_id>/update", methods=["GET", "POST"])
@login_required
def update_journal(journal_id):
    journal = Journal.query.get_or_404(journal_id)  # Get journal from database
    if (
        journal.user != current_user
    ):  # If journal does not belong to current user, abort
        abort(403)
    form = JournalForm()  # Create Journal Form
    if (
        form.validate_on_submit()
    ):  # If form is submitted, update journal and add to database
        journal.mood = form.mood.data
        journal.content = form.content.data
        db.session.commit()
        flash("Journal has been updated!", "success")
        return redirect(url_for("journals.journal", journal_id=journal.id))
    elif request.method == "GET":
        form.mood.data = journal.mood
        form.content.data = journal.content
    return render_template(
        "create_journal.html",
        title="Update Journal",
        legend="Update Journal",
        journal=journal,
        form=form,
    )


# Delete Journal Route
@journals.route("/journal/<int:journal_id>/delete", methods=["POST"])
@login_required
def delete_journal(journal_id):
    journal = Journal.query.get_or_404(journal_id)  # Get journal from database
    if (
        journal.user != current_user
    ):  # If journal does not belong to current user, abort
        abort(403)
    db.session.delete(journal)
    db.session.commit()
    flash("Journal has been deleted!", "success")
    return redirect(url_for("journals.all_journals"))

ChatbotWebsite/main/routes.py
from flask import render_template
from flask import Blueprint
from flask_login import current_user, login_required

main = Blueprint("main", __name__)


# Home Page
@main.route("/")
def home():
    return render_template("home.html", title="Mental Health Chatbot")


# About Page
@main.route("/about")
def about():
    return render_template("about.html", title="About")


# SOS Page
@main.route("/sos")
def sos():
    return render_template("sos.html", title="SOS")

ChatbotWebsite/users/routes.py
from flask import (
    current_app,
    Blueprint,
    render_template,
    request,
    jsonify,
    url_for,
    flash,
    redirect,
)
from flask_login import login_user, current_user, logout_user, login_required

from ChatbotWebsite import db, bcrypt
from ChatbotWebsite.models import User, ChatMessage, Journal
from ChatbotWebsite.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from ChatbotWebsite.users.utils import save_picture, send_reset_email
import os

users = Blueprint("users", __name__)


# register page/route
@users.route("/register", methods=["GET", "POST"])
def register():
    if (
        current_user.is_authenticated
    ):  # if user is already logged in, redirect to home page
        return redirect(url_for("main.home"))
    form = RegistrationForm()  # create registration form
    if (
        form.validate_on_submit()
    ):  # if form is submitted, create new user and add to database
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        new_user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(new_user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in.", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


# login page/route
@users.route("/login", methods=["GET", "POST"])
def login():
    if (
        current_user.is_authenticated
    ):  # if user is already logged in, redirect to home page
        return redirect(url_for("main.home"))
    form = LoginForm()  # create login form
    if (
        form.validate_on_submit()
    ):  # if form is submitted, check if user exists and password is correct
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You have been logged in!", "success")
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check email and password!", "danger")
    return render_template("login.html", title="Login", form=form)


# account page/route
@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()  # form to update account
    if form.validate_on_submit():
        if form.picture.data:
            old_picture = current_user.profile_image
            picture_file = save_picture(form.picture.data)
            current_user.profile_image = picture_file
            if old_picture != "default.jpg":
                os.remove(
                    os.path.join(
                        current_app.root_path, "static/profile_images", old_picture
                    )
                )
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template("account.html", title="Account", form=form)


# logout route
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


# delete conversation route
@users.route("/delete_conversation", methods=["POST"])
def delete_conversation():
    if current_user.is_authenticated:
        messages = ChatMessage.query.filter_by(user_id=current_user.id).all()
        for message in messages:
            db.session.delete(message)
        db.session.commit()
        flash("Your conversation has been deleted!", "success")
    return redirect(url_for("users.account"))


# delete account route
@users.route("/delete_account", methods=["POST"])
def delete_account():
    if current_user.is_authenticated:
        messages = ChatMessage.query.filter_by(user_id=current_user.id).all()
        for message in messages:
            db.session.delete(message)
        journals = Journal.query.filter_by(user_id=current_user.id).all()
        for journal in journals:
            db.session.delete(journal)
        db.session.delete(current_user)
        db.session.commit()
        flash("Your account has been deleted!", "success")
    return redirect(url_for("users.logout"))


# reset password route to request a password reset token
@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if (
        current_user.is_authenticated
    ):  # if user is already logged in, redirect to home page
        return redirect(url_for("main.home"))
    form = RequestResetForm()  # create request reset form
    if form.validate_on_submit():  # if form is submitted, send email with reset token
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


# reset password route to reset password
@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if (
        current_user.is_authenticated
    ):  # if user is already logged in, redirect to home page
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(user.password, form.password.data):
            flash(
                "Your new password must be unique and different from your old password.",
                "warning",
            )
            return redirect(url_for("users.reset_token", token=token, _external=True))
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

ChatbotWebsite/templates/account.html
{%extends "layout.html"%} {%block content%}
<div class="container py-4 h-100">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-5">
      <div class="card p-4 " style="border-radius: 15px;">
        <div class="d-flex text-black">
          <div class="flex-shrink-0">
            <img src="{{url_for(
              'static', filename='profile_images/' + current_user.profile_image)}}"
              alt="Profile image" class="img-fluid"
              style="height:180px; width: 180px; border-radius: 10px;">
          </div>
          <div class="col">
            <div class="row flex-grow-1 ms-3 mb-3">
              <h5 class="mb-1">#{{current_user.id}} {{current_user.username}}</h5>
              <p class="mb-2 pb-1" style="color: #2b2a2a;">{{current_user.email}}</p>
            </div>
            <div class="row flex-grow-1 ms-3">
              <div class="d-grid gap-3">
                <form action="{{url_for('users.delete_conversation')}}" method="POST">
                  <button type="submit" class="btn btn-outline-danger btn-sm">
                    Delete Conversation
                  </button>
                </form>
                <!-- Button trigger modal -->
                <div>
                  <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">
                    Delete Account
                  </button>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Account?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to delete your account? This action cannot be undone.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{{url_for('users.delete_account')}}" method="POST">
                          <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-sm px-5">
  <form method="POST" action="" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <fieldset class="form-group d-grid gap-3">
      <legend
        class="fs-1 fw-bold font-monospace border-bottom border-info mb-3 mt-2"
      >
        Account Info
      </legend>
      <div>
        {{form.username.label(class="form-control-label")}} {%if
        form.username.errors%} {{form.username(class="form-control
        form-control-lg is-invalid")}} {%for error in form.username.errors%}
        <div class="invalid-feedback">{{error}}</div>
        {%endfor%} {%else%} {{form.username(class="form-control
        form-control-lg")}} {%endif%}
      </div>
      <div class="form-group">
        {{form.email.label(class="form-control-label")}} {%if
        form.email.errors%} {{form.email(class="form-control form-control-lg
        is-invalid")}} {%for error in form.email.errors%}
        <div class="invalid-feedback">{{error}}</div>
        {%endfor%} {%else%} {{form.email(class="form-control form-control-lg")}}
        {%endif%}
      </div>
      <div class="form-group">
        {{form.picture(class="form-control-file")}}
        {% if form.picture.errors%}
            {%for error in form.picture.errors%}
                <span class="text-danger">{{error}}</div></br>
            {%endfor%}
        {%endif%}
      </div>
    </fieldset>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info btn-lg my-3")}}
    </div>
  </form>
</div>
{%endblock content%}

ChatbotWebsite/templates/create_journal.html
{% extends 'layout.html' %}
{% block content %}
<div class="container-sm px-5">
    <form method="POST" action="">
      {{form.hidden_tag()}}
      <fieldset class="form-group d-grid gap-3">
        <legend
          class="fs-1 fw-bold font-monospace border-bottom border-info mb-3 mt-2"
        >
          {{legend}}
        </legend>
        <div class="form-group">
          {{form.mood.label(class="form-control-label")}} {%if
          form.mood.errors%} {{form.mood(class="form-control form-control-lg
          is-invalid")}} {%for error in form.mood.errors%}
          <div class="invalid-feedback">{{error}}</div>
          {%endfor%} {%else%} {{form.mood(class="form-control form-control-lg")}}
          {%endif%}
        </div>
        <div class="form-group">
          {{form.content.label(class="form-control-label")}} {%if
          form.content.errors%} {{form.content(class="form-control
          form-control-lg is-invalid")}} {%for error in form.content.errors%}
          <div class="invalid-feedback">{{error}}</div>
          {%endfor%} {%else%} {{form.content(class="form-control
          form-control-lg",style="height:350px")}} {%endif%}
        </div>
      </fieldset>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info btn-lg mt-3")}}
      </div>
    </form>
  </div>

{% endblock content%}

ChatbotWebsite/templates/home.html
{%extends 'layout.html'%} {%block navigation%}{%endblock navigation%} {%block content%}
<div id="home-container" class="container-fluid d-grid gap-3">
  <img
    src="{{url_for('static',filename='images/chatbot.png')}}"
    alt="Mental Health Chatbot Picture"
    class="rounded-circle border border-secondary mt-3 mx-auto d-block shadow"
    style="width: 21.875rem; height: 21.875rem"
  />
  <h1
    id="chatbot-name"
    class="mx-auto my-2 fw-bold font-monospace border-bottom border-info"
  >
    Mental Health Chatbot
  </h1>



        {% if current_user.is_authenticated %}
        <a
          id="chat-now-link"
          class="btn btn-info mx-auto d-block"
          style="
            --bs-btn-padding-y: 1.25rem;
            --bs-btn-padding-x: 5.5rem;
            --bs-btn-font-size: 2rem;
            --bs-btn-font-weight: 700;
          "
          href="{{url_for('chatbot.chat')}}"
        >
          CHAT NOW
        </a>
        {% else %}
        <button
          id="start-now-link"
          class="btn btn-info mx-auto d-block"
          style="
            --bs-btn-padding-y: 1.25rem;
            --bs-btn-padding-x: 5.5rem;
            --bs-btn-font-size: 2rem;
            --bs-btn-font-weight: 700;
          "
          data-bs-toggle="modal"
          data-bs-target="#entryModal"
        >
        LOGIN / REGISTER
        </button>
        <div
          class="modal fade"
          id="entryModal"
          tabindex="-1"
          aria-labelledby="entryModalLabel"
          aria-hidden="true"
        >
          <div
            class="modal-dialog modal-dialog-centered modal-dialog-scrollable"
          >
            <div class="modal-content">
              <div class="modal-header border-bottom-0 pb-0">
                <h1 class="modal-title fw-bold font-monospace lh-sm">
                  Login / Register
                </h1>
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col d-flex flex-column align-items-center">
                    <small class="text-muted">Already Have an Account?</small>
                    <a
                      class="btn btn-outline-info btn-lg mt-1"
                      href="{{url_for('users.login')}}"
                      >Login Now</a
                    >
                  </div>
                  <div class="col d-flex flex-column align-items-center">
                    <small class="text-muted">New User? Wohoo</small>
                    <a
                      class="btn btn-outline-info btn-lg mt-1"
                      href="{{url_for('users.register')}}"
                      >Register Now</a
                    >
                  </div>
                </div>
              </div>
              <hr />
              <div class="modal-header border-bottom-0 pb-0">
                <h1 class="modal-title fw-bold font-monospace lh-sm">
                  Or as Guest
                </h1>
              </div>
              <div class="modal-body">
                <a
                  class="btn btn-outline-info btn-lg d-block"
                  href="{{url_for('chatbot.chat')}}"
                  style="--bs-btn-padding-x: 2.5rem"
                  >Continue</a
                >
              </div>
            </div>
          </div>
        </div>
        {%endif%}
      

    <a
      href="{{url_for('main.about')}}"
      id="about-me-link"
      class="btn btn-outline-info mx-auto d-block"
      style="
        --bs-btn-padding-y: 1.25rem;
        --bs-btn-padding-x: 5.5rem;
        --bs-btn-font-size: 2rem;
        --bs-btn-border-width: 0;
      "
    >
      About Us
    </a>
    {%if current_user.is_authenticated %}
        <a
          href="{{url_for('users.logout')}}"
          id="about-me-link"
          class="btn btn-outline-secondary mx-auto d-block"
          style="
            --bs-btn-padding-x: 3.5rem;
            --bs-btn-font-size: 1rem;
          "
        >
          Logout
        </a>
      {%endif%}
  </div>
  
  {%endblock content%}
</div>

ChatbotWebsite/templates/journal.html
{%extends 'layout.html'%}{%block content%}
    <div class="container-sm d-grid mt-5">
        <div class="container pt-1">
          <div class="row d-flex justify-content-center align-items-center">
              <div class="card mb-3 border-0">
                <div class="card-body p-4">
                  <h3 class="mb-3">Feeling <span class="text-info">{{journal.mood}}</span> on {{journal.timestamp.strftime('%d.%m.%Y')}}</h3>
                  <p class="lh-lg">{{journal.content}} </p>
                  <hr class="my-3">
                  <div class="d-flex justify-content-start align-items-center">
                    <img src="{{url_for('static',filename='profile_images/'+current_user.profile_image)}}" alt="profile-avatar"
                        class="img-fluid rounded-circle me-3" width="50">
                    <div class="col">
                        <p class="mb-0">{{journal.user.username}}</p>
                        <small class="text-muted">Created on {{journal.timestamp.strftime('%d/%m/%Y, %A, %H:%M')}}</small>
                    </div>
                    <div class="gap-3">
                        <a href="{{url_for('journals.update_journal',journal_id=journal.id)}}" class="btn btn-outline-secondary">Update</a>
                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteJournal">
                          Delete
                        </button>
                      </div>
                      <!-- Modal -->
                      <div class="modal fade" id="deleteJournal" tabindex="-1" aria-labelledby="deleteJournalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="deleteJournalLabel">Delete Journal?</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              Are you sure you want to delete your journal? This action cannot be undone.
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              <form action="{{url_for('journals.delete_journal',journal_id=journal.id)}}" method="POST">
                                <button type="submit" class="btn btn-danger">Delete</button>
                              </form>
                            </div>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <a href="{{url_for('journals.all_journals')}}" class="btn btn-outline-secondary col-1">&lt Back</a>
    </div>
    
{%endblock content%}

ChatbotWebsite/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/layout.css') }}"
    />
    {% block style%} {% endblock style %} {%block script%} {%endblock script%}
  </head>

  <body>
    <!-- As a heading -->
    {%block navigation%}
    <nav
      id="navigation-bar"
      class="navbar navbar-expand-lg bg-light.bg-gradient shadow-sm"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('main.home')}}"
          >Mental Health Bot</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse ml-5 d-flex justify-content-between"
          id="navbarNavDropdown"
        >
          <ul class="navbar-nav gap-3">
            <li class="nav-item bg-info text-black rounded">
              <a
                class="nav-link active fw-bold"
                aria-current="page"
                href="{{url_for('chatbot.chat')}}"
                >CHAT</a
              >
            </li>
            <li class="nav-item rounded">
              <a
                class="nav-link"
                aria-current="page"
                href="{{url_for('journals.all_journals')}}"
                >Journal</a
              >
            </li>
            <li class="nav-item rounded">
              <a
                class="nav-link"
                aria-current="page"
                href="{{url_for('main.about')}}"
                >About</a
              >
            </li>

          </ul>
          <ul class="navbar-nav gap-3">
            <li class="nav-item bg-danger rounded">
              <a class="sos nav-link active fw-bold" href="{{url_for('main.sos')}}">SOS</a>
            </li>
            {%if current_user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
            </li>
            {%endif%}
          </ul>
        </div>
      </div>
    </nav>
    {%endblock navigation%} {%with messages =
    get_flashed_messages(with_categories=true)%} {%if messages%} {%for category,
    message in messages%}
    <div
      class="alert alert-{{category}} position-absolute top-0 start-50 translate-middle-x"
    >
      {{message}}
    </div>
    {%endfor%} {%endif%}{%endwith%} {% block content%} {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script>const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
      const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))</script>
  </body>
</html>